version: 2.1

## adding an anchor for the docker image
docker_default_img: &default_img
    docker:
        - image: circleci/node:13.8.0

jobs:

    create_infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                  name: Create Cloudformation Stack
                  command: |
                      aws cloudformation deploy \
                        --template-file CloudFormationTemplate.yml \
                        --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                        --region us-east-1

    configure_infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["f2:7e:87:70:9b:0d:93:25:63:68:b4:52:6f:62:c4:50"]
            - run:
                name: Install Ansible
                # command: apk add --update ansible
                command: pip install -U ansible
            - run:
                name: Create an inventory file
                command: echo [all] > inventory
            - run:
                name: Add the ips to the inventory file
                command: |
                    aws ec2 describe-instances \
                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
                    --filters "Name=tag:Project,Values=udacity" \
                    --output text >> inventory
            - run:
                name: Run Playbook and Configure server
                command: ansible-playbook -i inventory playbook.yml

    test_job:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            # - run:
            #     name: Checking the aws cli
            #     command: aws iam list-users
            - run:
                name: Getting Ansible
                command: ls -la /usr/local/bin

workflows:
    AWSworkflow:
        jobs:
            # - create_infrastructure
            # - configure_infrastructure:
            #     requires: [create_infrastructure]
            - test_job