version: 2.1

## adding an anchor for the docker image
docker_default_img: &default_img
    docker:
        - image: circleci/node:13.8.0

jobs:
    create_infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                  name: Create Cloudformation Stack
                  command: |
                      aws cloudformation deploy \
                        --template-file template.yml \
                        --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                        --region us-east-1

workflows:
    AWSworkflow:
        jobs:
            - create_infrastructure