---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

## extract the files
- name: copying files
  # shell: pm2 start ~/web/index.js -f
  copy:
    src: ../artifact.tar.gz
    dest: /home/ubuntu/backend
