---
## copy files to the instance
- name: Copying index test page
  template:
    src: ../artifact.tar.gz
    dest: ~/artifact.tar.gz

## extract the files
- name: extracting files
  # shell: pm2 start ~/web/index.js -f
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend_files