---
# ## copy files to the instance
# - name: Copying index test page
#   template:
#     src: ../artifact.tar.gz
#     dest: ~/artifact.tar.gz

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory


## extract the files
- name: extracting files
  # shell: pm2 start ~/web/index.js -f
  unarchive:
    src: ../artifact.tar.gz
    dest: /home/ubuntu/backend

## various jobs
- name: test jobs
  shell: |
    ls -la
    pwd
    cd ..
    ls -la
    pwd

